{"name": "test_login", "status": "broken", "statusDetails": {"message": "AttributeError: 'tuple' object has no attribute 'value'", "trace": "self = <testcase.test_login_demo.TestLogin object at 0x000001EF00BDA9B0>\n\n    def test_login(self):\n        ws = load_workbook(data)\n        ws.save(data_res)\n        ws_res = load_workbook(data_res)\n        st_res = ws_res[\"app\"]\n        for i in range(0,6):\n            if (excel[i]['是否执行']) != 'Y':\n                print('此版本不测试')\n            else:\n                url = excel[i]['请求URL']  # 接口URL\n                method = excel[i]['请求方法']  #请求方法\n                d = eval(excel[i]['请求参数'])  #获取传入接口的参数\n                r = request(url=url,method=method,data=d)\n                print(r.text)\n                try:\n                    assert int(excel[i]['状态码']) == r.json()['msg_code']  #断言响应码\n                    assert excel[i]['返回信息'] == r.json()['msg']  #断言响应信息\n>                   st_res[\"k\"] = 'PASS'\n\ntest_login_demo.py:36: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Worksheet \"app\">, key = 'k', value = 'PASS'\n\n    def __setitem__(self, key, value):\n>       self[key].value = value\nE       AttributeError: 'tuple' object has no attribute 'value'\n\n..\\..\\..\\..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\openpyxl\\worksheet\\worksheet.py:313: AttributeError\n\nDuring handling of the above exception, another exception occurred:\n\nself = <testcase.test_login_demo.TestLogin object at 0x000001EF00BDA9B0>\n\n    def test_login(self):\n        ws = load_workbook(data)\n        ws.save(data_res)\n        ws_res = load_workbook(data_res)\n        st_res = ws_res[\"app\"]\n        for i in range(0,6):\n            if (excel[i]['是否执行']) != 'Y':\n                print('此版本不测试')\n            else:\n                url = excel[i]['请求URL']  # 接口URL\n                method = excel[i]['请求方法']  #请求方法\n                d = eval(excel[i]['请求参数'])  #获取传入接口的参数\n                r = request(url=url,method=method,data=d)\n                print(r.text)\n                try:\n                    assert int(excel[i]['状态码']) == r.json()['msg_code']  #断言响应码\n                    assert excel[i]['返回信息'] == r.json()['msg']  #断言响应信息\n                    st_res[\"k\"] = 'PASS'\n                except Exception as e:\n>                   st_res[\"k\"] = e\n\ntest_login_demo.py:38: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nself = <Worksheet \"app\">, key = 'k'\nvalue = AttributeError(\"'tuple' object has no attribute 'value'\",)\n\n    def __setitem__(self, key, value):\n>       self[key].value = value\nE       AttributeError: 'tuple' object has no attribute 'value'\n\n..\\..\\..\\..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\openpyxl\\worksheet\\worksheet.py:313: AttributeError"}, "start": 1656909050858, "stop": 1656909051914, "uuid": "e3c6cdad-09b2-4a2d-b538-4165f1d4ca11", "historyId": "966da4c978c322b6b1d09eb1e0322926", "testCaseId": "635f167e9ec99310021d4ad82ace208f", "fullName": "test_login_demo.TestLogin#test_login", "labels": [{"name": "suite", "value": "test_login_demo"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "22424-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_demo"}]}