{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "d6d85b96-5b1b-4729-8a80-594627c16af2-attachment.attach"}], "start": 1651988348369, "stop": 1651988348369}], "attachments": [{"name": "截图", "source": "d4190499-f501-43f1-875e-03e4592400a5-attachment.png", "type": "image/png"}, {"name": "截图", "source": "59747d1c-0ba5-4f3c-ae70-9ffc8aeb95ea-attachment.png", "type": "image/png"}], "start": 1651988348368, "stop": 1651988352626, "uuid": "45adc56a-69fa-4c0f-81c2-3cb798a0c99e", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "xxx测试"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "17260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}