{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "5db183d0-1f77-4853-a492-20e40f99a878-attachment.attach"}], "start": 1651988419545, "stop": 1651988419546}], "attachments": [{"name": "截图", "source": "bcacf0b6-d96f-474e-bd35-49e05fdaf8cf-attachment.png", "type": "image/png"}, {"name": "截图", "source": "bd2a0e27-17c8-4428-8e98-a730b1cf3221-attachment.png", "type": "image/png"}], "start": 1651988419545, "stop": 1651988422887, "uuid": "3acaa99a-72d5-4c8f-a51a-e31bee61c039", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "14400-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}