{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "e89ca0c0-b3a4-4f30-b028-1e20298eed71-attachment.attach"}], "start": 1651988354427, "stop": 1651988354427}], "attachments": [{"name": "截图", "source": "ea983f7b-544d-4dcc-a570-3420852f1977-attachment.png", "type": "image/png"}, {"name": "截图", "source": "5aedf451-4315-45ad-8191-278ac5b4c0e3-attachment.png", "type": "image/png"}], "start": 1651988354427, "stop": 1651988355727, "uuid": "47e677d4-363f-4824-a0ac-4b384dc8ca50", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "severity", "value": "critical"}, {"name": "epic", "value": "xxx测试"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "17260-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}