{"name": "测试用例描述：查询客户数据", "status": "failed", "statusDetails": {"message": "AssertionError: assert [['1', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']] == [['2', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']]", "trace": "self = <testcase.test_one.Testmysql object at 0x0000024BA9793E80>, action = None\n\n    @allure.story('用户故事描述：查询数据')  # 模块的功能\n    @allure.description('测试描述：查询数据是否正确')\n    @allure.title('测试用例描述：查询客户数据')\n    @allure.severity(allure.severity_level.BLOCKER)\n    def test_03(self,action):\n        db = pymysql.connect(host = '192.168.0.219',port =3306,db='test',user='root',passwd='123',charset='utf8')\n        info = db.cursor()\n        info.execute('select id,username from sec_custinfo')\n        data = info.fetchall()\n        ret =[]\n        for one,two in data:\n            line = one\n            line1 = two\n            ret.append([line,line1])\n        print(ret)\n        #结果：[['1', '董卓'], ['2', '张坤'], ['3', '王伟']]\n        with allure.step(\"查询\"):\n            allure.attach('select id,username from sec_custinfo',name='sql执行')\n        with allure.step(\"响应\"):\n            allure.attach('{}'.format(ret),name='返回结果')\n        with allure.step(\"断言\"):\n>           assert ret == yaml_data['except']\nE           AssertionError: assert [['1', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']] == [['2', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']]\n\ntest_one.py:35: AssertionError"}, "description": "测试描述：查询数据是否正确", "steps": [{"name": "查询", "status": "passed", "attachments": [{"name": "sql执行", "source": "cd54e5cf-8a9a-45d5-8bac-1e22c14fdc89-attachment.attach"}], "start": 1651929039149, "stop": 1651929039149}, {"name": "响应", "status": "passed", "attachments": [{"name": "返回结果", "source": "551bab86-720a-4ec0-81ad-6fae3fd66a53-attachment.attach"}], "start": 1651929039149, "stop": 1651929039149}, {"name": "断言", "status": "failed", "statusDetails": {"message": "AssertionError: assert [['1', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']] == [['2', '董卓'],\\n ['2', '张坤'],\\n ['3', '王伟'],\\n ['4', '王伟'],\\n ['5', '宋军'],\\n ['6', '陈红'],\\n ['7', '陈红'],\\n ['8', '王丽'],\\n ['9', '王丽'],\\n ['10', '宋伟']]\n", "trace": "  File \"C:\\Users\\Administrator\\.jenkins\\workspace\\psimsendemail\\untitled\\testcase\\test_one.py\", line 35, in test_03\n    assert ret == yaml_data['except']\n"}, "start": 1651929039149, "stop": 1651929039150}], "start": 1651929039146, "stop": 1651929039150, "uuid": "672dfa7a-9fc3-4395-a955-98df1ab8b927", "historyId": "e80dcb360667126e504de2bd04d2fb61", "testCaseId": "673d513ad150bc91b8f870520ad0cdeb", "fullName": "test_one.Testmysql#test_03", "labels": [{"name": "severity", "value": "blocker"}, {"name": "feature", "value": "数据库"}, {"name": "epic", "value": "*************测试描述*************"}, {"name": "story", "value": "用户故事描述：查询数据"}, {"name": "suite", "value": "test_one"}, {"name": "subSuite", "value": "Testmysql"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "12420-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_one"}]}