{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "afd21242-147b-4fb7-aa51-034807738096-attachment.attach"}], "start": 1651987636199, "stop": 1651987636208}], "attachments": [{"name": "截图", "source": "26755de5-b10e-49d5-a38a-bb8d427f643b-attachment.png", "type": "image/png"}, {"name": "截图", "source": "b9a5e95e-1e7f-4986-a818-4022a4a42820-attachment.png", "type": "image/png"}], "start": 1651987636199, "stop": 1651987637647, "uuid": "0b3d5e45-8fe6-4958-a5d9-b2e9841c0027", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "登录"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "16428-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}