{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "46cd343a-13ad-4ba5-8031-6078e318d444-attachment.attach"}], "start": 1651989224430, "stop": 1651989224430}], "attachments": [{"name": "截图", "source": "ac5a61cc-da30-420a-8499-cdd103f5c18d-attachment.png", "type": "image/png"}, {"name": "截图", "source": "1625cf0d-e7f5-4875-be28-c5e245e61726-attachment.png", "type": "image/png"}], "start": 1651989224429, "stop": 1651989229077, "uuid": "1fc7d2f0-8110-401d-ac7e-77e88cbc486c", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "15172-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}