{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "b2e64efe-03d5-4624-8ae3-3091ed391873-attachment.attach"}], "start": 1651989267977, "stop": 1651989267978}], "attachments": [{"name": "截图", "source": "aa8b9838-9946-4438-9a96-90761875882c-attachment.png", "type": "image/png"}, {"name": "截图", "source": "2ae5654a-5b1a-4b94-a1c1-0fe2a76fee26-attachment.png", "type": "image/png"}], "start": 1651989267977, "stop": 1651989269268, "uuid": "276843e3-0d7b-4749-93d1-fd0cb5329201", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "epic", "value": "xxx测试"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "15092-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}