{"name": "测试用例描述：错误的验证码登录失败", "status": "passed", "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "c83be5c7-6c3a-4830-ade4-242226e5a315-attachment.attach"}], "start": 1651988000987, "stop": 1651988000988}], "attachments": [{"name": "截图", "source": "4998067c-1094-4f3d-a40f-2475e0ca2354-attachment.png", "type": "image/png"}, {"name": "截图", "source": "e6d92616-c7fe-45a6-b3d3-a3d2280e28ed-attachment.png", "type": "image/png"}], "start": 1651988000987, "stop": 1651988002226, "uuid": "ddfed6d0-0236-4f50-b0e0-f10fb53f1580", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "登录"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "18340-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}