{"name": "测试用例描述：错误的验证码登录失败", "status": "broken", "statusDetails": {"message": "TypeError: object of type 'NoneType' has no len()", "trace": "self = <testcase.test_two.Test object at 0x000001D257DBE470>\n\n    @allure.severity(allure.severity_level.CRITICAL)\n    @allure.story(\"登录\")\n    @allure.description('测试描述：错误的验证码登录失败')\n    @allure.title('测试用例描述：错误的验证码登录失败')\n    def test_23(self):\n        with allure.step(\"输入错误的验证码\"):\n            allure.attach('{}'.format(Test.yaml_data['Login3']['username']), name='错误的验证码')\n        aa = LoginPage(Test.driver)\n        aa.test_login(Test.yaml_data['Login3']['username'], Test.yaml_data['Login3']['password'],\n>                     Test.yaml_data['Login3']['Verification'])\n\ntest_two.py:135: \n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n..\\pageobject\\login_page.py:36: in test_login\n    raise e\n..\\pageobject\\login_page.py:30: in test_login\n    self.send_keys(self.Verification_loc,Verification)\n..\\base\\base_page.py:29: in send_keys\n    self.locator_element(loc).send_keys(value)\n..\\..\\..\\..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\selenium\\webdriver\\remote\\webelement.py:478: in send_keys\n    {'text': \"\".join(keys_to_typing(value)),\n_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _\n\nvalue = (None,)\n\n    def keys_to_typing(value):\n        \"\"\"Processes the values that will be typed in the element.\"\"\"\n        typing = []\n        for val in value:\n            if isinstance(val, Keys):\n                typing.append(val)\n            elif isinstance(val, int):\n                val = str(val)\n                for i in range(len(val)):\n                    typing.append(val[i])\n            else:\n>               for i in range(len(val)):\nE               TypeError: object of type 'NoneType' has no len()\n\n..\\..\\..\\..\\..\\AppData\\Roaming\\Python\\Python36\\site-packages\\selenium\\webdriver\\common\\utils.py:150: TypeError"}, "description": "测试描述：错误的验证码登录失败", "steps": [{"name": "输入错误的验证码", "status": "passed", "attachments": [{"name": "错误的验证码", "source": "8abed693-e8f6-407c-b803-73db1fe6073c-attachment.attach"}], "start": 1651986334593, "stop": 1651986334593}], "start": 1651986334593, "stop": 1651986335425, "uuid": "c47e0c9d-8e57-4b85-8aad-071bee72ea17", "historyId": "2d7cab507b6851b7595fa5868d612dc0", "testCaseId": "a971ec309964150e721c6794e448f50a", "fullName": "test_two.Test#test_23", "labels": [{"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "5808-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}