{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "fe0411a6-fb70-42aa-98c3-e2f10d09439e-attachment.attach"}], "start": 1651988646475, "stop": 1651988646475}], "attachments": [{"name": "截图", "source": "a5e3dac4-f44a-4b43-a3d5-c5c858c46752-attachment.png", "type": "image/png"}, {"name": "截图", "source": "837708f1-0c2a-4bb3-8a9b-9b3871f489fa-attachment.png", "type": "image/png"}], "start": 1651988646475, "stop": 1651988649667, "uuid": "d1398c3f-1a77-440a-a90d-3b74045f82c7", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "epic", "value": "xxx测试"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "17840-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}