{"name": "测试用例描述：正确的账号密码登录成功", "status": "broken", "statusDetails": {"message": "AttributeError: 'Test' object has no attribute 'driver'", "trace": "self = <testcase.test_four.Test object at 0x00000200C8328BE0>\n\n    def setup(self):\n>       driver = self.driver\nE       AttributeError: 'Test' object has no attribute 'driver'\n\ntest_four.py:19: AttributeError"}, "description": "测试描述：正确的账号密码登录成功", "start": 1651822582024, "stop": 1651822582024, "uuid": "50a8b711-859e-4dff-9eb2-ba345c09d0cc", "historyId": "1a2fe18af852af85557a37dca4ea131b", "testCaseId": "c4abd6df2c1fb32ea5cc8bf06688822d", "fullName": "test_four.Test#test_01", "labels": [{"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "feature", "value": "登录模块"}, {"name": "severity", "value": "critical"}, {"name": "suite", "value": "test_four"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "3940-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_four"}]}