{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "694f8503-0fee-4c8f-9107-65ea8d00bada-attachment.attach"}], "start": 1651989184731, "stop": 1651989184732}], "attachments": [{"name": "截图", "source": "1fb111b5-0ffa-489f-88f7-a2c03f4a4a77-attachment.png", "type": "image/png"}, {"name": "截图", "source": "b8a7c02a-5847-4bc1-a197-0e95940ef4b1-attachment.png", "type": "image/png"}], "start": 1651989184731, "stop": 1651989191384, "uuid": "c9e77a7b-9776-4ee9-a06f-19c568fd8463", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "story", "value": "登录"}, {"name": "epic", "value": "xxx测试"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "14312-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}