{"name": "测试用例描述：错误的账号登录失败", "status": "passed", "description": "测试描述：错误的账号登录失败", "steps": [{"name": "输入错误的账号", "status": "passed", "attachments": [{"name": "错误的账号", "source": "b398d6ca-79e8-4881-a2b5-6ffb5da4310c-attachment.attach"}], "start": 1651988936319, "stop": 1651988936319}], "attachments": [{"name": "截图", "source": "fb4f798e-0022-4df9-80b2-704186ea05d1-attachment.png", "type": "image/png"}, {"name": "截图", "source": "b01f0c22-6b9f-4019-b037-9a6a3b36ca4a-attachment.png", "type": "image/png"}], "start": 1651988936318, "stop": 1651988941667, "uuid": "2a506e00-7d23-4a7f-8e66-0af22c277df4", "historyId": "07ccc934c01f5e078d85f2f38ccbb5fd", "testCaseId": "07642125497ce5d4c888927c76cac843", "fullName": "test_two.Test#test_21", "labels": [{"name": "severity", "value": "critical"}, {"name": "epic", "value": "xxx测试"}, {"name": "feature", "value": "登录模块"}, {"name": "story", "value": "登录"}, {"name": "suite", "value": "test_two"}, {"name": "subSuite", "value": "Test"}, {"name": "host", "value": "MS-SLSXLICKSUSF"}, {"name": "thread", "value": "14540-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_two"}]}